DROP TABLE NOBLE_WIN;

CREATE TABLE NOBLE_WIN(
    YEARS INTERGER, 
    SUBJECT TEXT,
    WINNER TEXT,
    COUNTRY TEXT,
    CATEGORY TEXT
);

INSERT INTO NOBLE_WIN(YEARS,SUBJECT,WINNER,COUNTRY,CATEGORY)
VALUES
(2010,'PHYSICS', 'AMULYA','INDIA','SCIENTIST'),
(1989,'CHEMISTRY','ATULYA' ,'INDIA','SCIENTIST'),
(1976,'BIOLOGY','HI','UK','SCIENTIST'),
(1999,'PHYSICS','BYE','US','SCIENTIST'),
(2003,'MATHEMATICS','RAM','SRI LANKA','MATHEMATICIAN'),
(2023,'COMPUTERS','SHYAM','INDIA','TECH'),
(2021,'GEO','WHY','FRANCE','MAPPING');

SELECT * FROM NOBLE_WIN WHERE SUBJECT NOT LIKE 'P%' ORDER BY YEARS DESC;
SELECT * FROM NOBLE_WIN WHERE SUBJECT NOT LIKE 'P%' ORDER BY WINNER;
